### ISSUE TITLE
What's the GAP package required for installing the current package?

### ISSUE THREAD

**Issue by zzygyx9119** [ndbrown6/MSK-GRAIL-TECHVAL#2]
when trying to install MSK-GRAIL-TECHVAL package, I got an error saying "GAP package is required".  However, I couldn't find GAP package. Could you please let me know what this GAP package is and where to find it. 

I would greatly appreciate your kind help!

Jeff

**Comment by ndbrown6** [comment]
Hi Jeff,

You can't "install" this repo as an R library. I wanted to do so but time considerations prevented me from getting there and I had to freeze this version for publication. All the R scripts are still functional given the data sources in the manuscript. `GAP` is a proper standalone R library though. You can find it here https://github.com/ndbrown6/GAP

Hope that helps

Kind regards
David

**Comment by zzygyx9119** [comment]
Hi David,

Thank you for your kind help!

Best,

Jeff
